---
galaxy_info:
  role_name: rhbase
  company: ClusterApps
  author: Michael Cleary
  description: Base setup of a server with a RedHat-based Linux distribution with the systemd init system.
  license: BSD
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system
dependencies: []
