---
rhbase_systemd_services:
  - systemd-journald
  - systemd-tmpfiles-setup-dev
  - systemd-tmpfiles-setup

rhbase_dependencies:
  - libselinux-python
  - libsemanage-python
  - policycoreutils-python
  - firewalld
  - dbus-python
  - tmux
  - net-tools
  - tcpdump 
  - rsync
  - rsyslog 
  

rhbase_package_manager: yum
rhbase_package_manager_configuration: /etc/yum.conf
