---
- name: Admin | Add task runners group
  group:
    name: "taskrunners"
    state: present
  tags:
    - rhbase
    - admin

- name: Admin | Add task runner user
  user:
    name: taskrunner
    state: present
    comment: "Task Runner"
    shell: "/bin/bash"
    groups: "taskrunners"
  tags:
    - rhbase
    - admin

- name: Admin | Task Runners sudo
  lineinfile:
    dest: /etc/sudoers.d/taskrunners
    state: present
    create: yes
    regexp: '^%taskrunners'
    line: '%taskrunners ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - rhbase
    - admin

- name: "Admin | Set up keys for Task Runner"
  authorized_key:
    user: taskrunner
    key: "{{ rhbase_taskrunner_key }}"
    exclusive: True
  when: rhbase_taskrunner_key is defined  
  tags:
    - rhbase
    - admin