---

galaxy_info:
  author: 'Simon Bärlocher'
  company: 'sbaerlo.ch/er'
  description: 'Installing and Configuration SNMP v3 on Linux and SNMP v2 on Windows.'
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - system
    - networking
    - monitoring

dependencies: []
