---
# tasks file for vim
- name: Install required packages
  package:
          name: "{{ install_packages }}"
          state: present
  become: true
  tags:
          - install_packages

- name: Ensure .vim/{autoload,bundle} directory exists
  file:
          path: "{{ item }}"
          state: directory
          recurse: false
          mode: 0750
  loop:
          - "{{ vim_dir }}"
          - "{{ vim_dir }}/autoload"
          - "{{ vim_dir }}/bundle"

- name: Ensure Pathogen is in place
  get_url:
          dest: "{{ vim_dir }}/autoload/pathogen.vim"
          url: https://tpo.pe/pathogen.vim
          mode: 0777

- name: Deploy plugins
  git:
          dest: "{{ vim_dir }}/bundle/{{ item.name }}"
          repo: "{{ item.url }}"
          clone: true
          update: true
          recursive: false
          version: master
  loop: "{{ plugins }}"

- name: Ensure .vimrc config in place
  copy:
          src: vimrc
          dest: "{{ vimrc }}"
          backup: true
          mode: 0640
