---
- name: updatepackages
  apt:
      autoclean: true
      update_cache: true
      upgrade: true
      force_apt_get: true

- name: Install common packages
  apt:
      name: "{{ item }}"
      force_apt_get: true
  with_items: "{{ common_packages }}"
